# Generated by Django 6.0.7 on 2026-08-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunkloop', '0008_conversation_message_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='domains',
            field=models.JSONField(blank=True, default=list, help_text='List of allowed email domains for this university, e.g. ["thapar.edu", "thapar.ac.in"]. Leave empty to allow any academic domain (fallback to .edu/.ac. check).'),
        ),
    ]
