# Generated by Django 6.0.7 on 2026-08-29 15:57
# Seeds universities with their allowed email domains list

from django.db import migrations


def seed_universities(apps, schema_editor):
    University = apps.get_model('bunkloop', 'University')
    seeds = [
        ('Thapar University', ['thapar.edu']),
        ('Chandigarh University', ['cuchd.in', 'cumail.in']),
        ('Chitkara University', ['chitkara.edu.in', 'chitkara.edu']),
        ('Lovely Professional University', ['lpu.co.in', 'lpu.in']),
        ('PEC University of Technology', ['pec.edu.in', 'pec.ac.in']),
        ('Punjab University', ['pu.ac.in', 'puchd.ac.in']),
    ]
    for name, domains in seeds:
        uni, created = University.objects.get_or_create(name=name)
        # Update domains if empty or different (normalize via model clean)
        if not uni.domains or set(uni.domains) != set(domains):
            uni.domains = domains
            try:
                uni.full_clean()
                uni.save()
            except Exception:
                # Fallback without full_clean for old data
                University.objects.filter(pk=uni.pk).update(domains=domains)


def unseed_universities(apps, schema_editor):
    University = apps.get_model('bunkloop', 'University')
    # Do not delete, just clear domains for reversal
    for name in ['Thapar University', 'Chandigarh University', 'Chitkara University', 'Lovely Professional University', 'PEC University of Technology', 'Punjab University']:
        try:
            uni = University.objects.get(name=name)
            uni.domains = []
            uni.save()
        except University.DoesNotExist:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('bunkloop', '0009_university_domains'),
    ]

    operations = [
        migrations.RunPython(seed_universities, unseed_universities),
    ]
